import type { NextPage } from 'next'
import Head from 'next/head'
import { useWeb3, useSwitchNetwork } from '@3rdweb/hooks'
import {
  Box,
  Button,
  Container,
  Flex,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Text,
} from '@chakra-ui/react'
import { HiChevronDown } from 'react-icons/hi'
import { IoMdWallet } from 'react-icons/io'

const NetworkMetadata = (props: {
  icon: React.ComponentType | string
  chainName: string
  symbol: string
  isTestnet: boolean
}) => {
  const { chainName } = props
  if (!props || !chainName) {
    return <></>
  }
  const { icon, symbol, isTestnet } = props

  const ChainIconElement = icon
  const iconSize = symbol === 'MATIC' ? 5 : 3

  return (
    <Flex gap={2}>
      <Box w={iconSize} h={iconSize}>
        <ChainIconElement />
      </Box>
      <Text>{chainName}</Text>
      {isTestnet && <Text color="grey">(testnet)</Text>}
    </Flex>
  )
}

const CustomConnect = () => {
  const web3 = useWeb3()

  const {
    address,
    chainId,
    connectWallet,
    disconnectWallet,
    getNetworkMetadata,
  } = web3
  const { switchNetwork } = useSwitchNetwork()

  let networkMetadata = null

  if (chainId) {
    networkMetadata = getNetworkMetadata(chainId)
  }

  // If a wallet is connected, show disconnect and switch network options
  return (
    <>
      {address ? (
        <Menu>
          <MenuButton minH={10} as={Button} rightIcon={<HiChevronDown />}>
            {networkMetadata && <NetworkMetadata {...networkMetadata} />}
          </MenuButton>
          <MenuList>
            <MenuItem onClick={() => switchNetwork(80001)}>
              Switch to Polygon Mumbai
            </MenuItem>
            <MenuItem onClick={() => switchNetwork(4)}>
              Switch to Rinkeby
            </MenuItem>
            <MenuItem onClick={disconnectWallet}>Switch Wallet</MenuItem>
          </MenuList>
        </Menu>
      ) : (
        <>
          <Button
            onClick={() => connectWallet('injected')}
            leftIcon={<IoMdWallet />}
            colorScheme="purple"
          >
            Connect MetaMask
          </Button>
        </>
      )}
    </>
  )
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web3 Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.md">
        <Flex flexDirection="column" w="100%" h="100%">
          <Flex justifyContent="flex-end" m={5}>
            <CustomConnect />
          </Flex>
        </Flex>
      </Container>
    </>
  )
}

export default Home


// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://devpost.com/software/theescrow?ref_content=user-portfolio&ref_feature=in_progress">TheEscrow!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by checking out our Jobs!
//           {/* <code className={styles.code}>pages/index.js</code> */}
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Create a logo for me &rarr;</h2>
//             <p>Design a good looking logo for my company.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Build a website &rarr;</h2>
//             <p>Program an interactive website using React!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Take a video for me &rarr;</h2>
//             <p>Film an animal in the wild for my YouTube Channel.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Spend the day with me &rarr;</h2>
//             <p>
//               Become my best friend for a day.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }